import { LineGraphInterface } from "./interfaces";

export const dataSetFeb: LineGraphInterface = {
  labels: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
  ],
  datasets: [
    {
      data: [
        86,
        114,
        80,
        60,
        25,
        31,
        58,
        17,
        70,
        50,
        86,
        114,
        80,
        60,
        25,
        31,
        58,
        17,
        70,
        50,
        86,
        114,
        80,
        60,
        25,
        31,
        58,
        17,
        70,
        50,
      ],
      label: "BloodTest",
      borderColor: "#3e95cd",
      fill: false,
    },
    {
      data: [
        82,
        50,
        11,
        52,
        35,
        89,
        47,
        12,
        28,
        60,
        82,
        50,
        11,
        52,
        35,
        89,
        47,
        12,
        28,
        60,
        82,
        50,
        11,
        52,
        35,
        89,
        47,
        12,
        28,
        60,
      ],
      label: "Hemoglobin",
      borderColor: "#8e5ea2",
      fill: false,
    },
    {
      data: [
        68,
        7,
        18,
        10,
        23,
        26,
        68,
        7,
        18,
        10,
        23,
        26,
        48,
        47,
        65,
        34,
        48,
        47,
        65,
        34,
        68,
        7,
        18,
        10,
        23,
        26,
        48,
        47,
        65,
        34,
      ],
      label: "Hepatitis",
      borderColor: "#3cba9f",
      fill: false,
    },
    {
      data: [
        40,
        20,
        10,
        16,
        24,
        38,
        40,
        20,
        10,
        16,
        24,
        38,
        74,
        167,
        58,
        74,
        74,
        167,
        58,
        40,
        20,
        10,
        16,
        24,
        38,
        74,
        167,
        58,
        74,
        74,
      ],
      label: "RibbonTest",
      borderColor: "#e8c3b9",
      fill: false,
    },
    {
      data: [
        6,
        3,
        6,
        3,
        2,
        2,
        7,
        26,
        22,
        12,
        6,
        3,
        6,
        3,
        2,
        2,
        7,
        26,
        22,
        12,
        12,
        43,
        2,
        2,
        7,
        26,
        22,
        12,
        12,
        43,
      ],
      label: "CoronaTest",
      borderColor: "#c45850",
      fill: false,
    },
  ],
};

export const dataSetJan: LineGraphInterface = {
  labels: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
  ],
  datasets: [
    {
      data: [
        86,
        114,
        80,
        60,
        25,
        31,
        58,
        17,
        17,
        70,
        50,
        86,
        114,
        80,
        60,
        25,
        31,
        114,
        80,
        60,
        25,
        31,
        58,
        17,
        70,
        50,
        86,
        58,
        70,
        50,
      ],
      label: "BloodTest",
      borderColor: "#3e95cd",
      fill: false,
    },
    {
      data: [
        47,
        12,
        28,
        60,
        82,
        50,
        11,
        52,
        35,
        89,
        50,
        60,
        82,
        50,
        11,
        82,
        89,
        47,
        12,
        11,
        52,
        35,
        89,
        52,
        35,
        47,
        12,
        28,
        28,
        60,
      ],
      label: "Hemoglobin",
      borderColor: "#8e5ea2",
      fill: false,
    },
    {
      data: [
        68,
        7,
        18,
        10,
        23,
        26,
        68,
        7,
        18,
        10,
        23,
        26,
        48,
        47,
        65,
        34,
        48,
        47,
        65,
        34,
        68,
        7,
        18,
        10,
        23,
        26,
        48,
        47,
        65,
        34,
      ],
      label: "Hepatitis",
      borderColor: "#3cba9f",
      fill: false,
    },
    {
      data: [
        40,
        20,
        10,
        16,
        74,
        74,
        167,
        58,
        40,
        20,
        10,
        16,
        24,
        38,
        24,
        38,
        40,
        20,
        10,
        16,
        24,
        38,
        74,
        167,
        58,
        74,
        167,
        58,
        74,
        74,
      ],
      label: "RibbonTest",
      borderColor: "#e8c3b9",
      fill: false,
    },
    {
      data: [
        6,
        3,
        6,
        6,
        3,
        6,
        3,
        2,
        2,
        7,
        26,
        22,
        12,
        3,
        2,
        2,
        7,
        26,
        22,
        12,
        12,
        43,
        2,
        2,
        7,
        26,
        22,
        12,
        12,
        43,
      ],
      label: "CoronaTest",
      borderColor: "#c45850",
      fill: false,
    },
  ],
};

export const dataWithTests = [
  { name: "1", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "2", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "3", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "4", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "5", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "6", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "7", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "8", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "9", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
  { name: "10", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
  { name: "11", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "12", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "13", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "14", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "15", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "16", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "17", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "18", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "19", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
  { name: "20", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
  { name: "21", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "22", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "23", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "24", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "25", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "26", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "27", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "28", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "29", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
  { name: "30", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
];

export const data = [
  { name: "1", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "2", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "3", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "4", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "5", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "6", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "7", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
  { name: "8", "total": 13, "blood": 2 , "hemoglobin": 5, "corona": 8},
  { name: "9", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "10", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "11", "total": 8 , "blood": 2, "hemoglobin": 1, "corona": 5},
  { name: "12", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "13", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "14", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "15", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
  { name: "16", "total": 14 , "blood": 1, "hemoglobin": 7, "corona": 6},
  { name: "17", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "18", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "19", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "20", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
  { name: "21", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
  { name: "22", "total": 10, "blood": 1 , "hemoglobin": 3, "corona": 6},
  { name: "23", "total": 10, "blood": 3, "hemoglobin": 4, "corona": 3 },
  { name: "24", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "25", "total": 15, "blood": 5, "hemoglobin": 6, "corona": 4 },
  { name: "26", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "27", "total": 4 , "blood": 2, "hemoglobin": 0, "corona": 2},
  { name: "28", "total": 7, "blood": 1 , "hemoglobin": 2, "corona": 5},
  { name: "29", "total": 22 , "blood": 7, "hemoglobin": 10, "corona": 5},
  { name: "30", "total": 12, "blood": 4 , "hemoglobin": 6, "corona": 2},
];

// function totalAllAppointmentData() {
//   const countOfAppointments: number[] = [];
//   let counter: number = 0;

//   while (counter <= 30) {
//     countOfAppointments.push(0);
//     APIRESPONSE.dataSetFeb.datasets.forEach(
//       (obj) =>
//         (countOfAppointments[counter] =
//           obj.data[counter] + countOfAppointments[counter])
//     );

//     counter++;
//   }

//   // console.log(countOfAppointments);
//   APIRESPONSE.dataSetFeb.datasets.push({
//     data: countOfAppointments,
//     label: "TotalVisits",
//     borderColor: "#c42150",
//     fill: false,
//   });
// }

// function totalAllAppointmentDataJan() {
//   const countOfAppointments: number[] = [];
//   let counter: number = 0;

//   while (counter <= 30) {
//     countOfAppointments.push(0);
//     APIRESPONSE.dataSetJan.datasets.forEach(
//       (obj) =>
//         (countOfAppointments[counter] =
//           obj.data[counter] + countOfAppointments[counter])
//     );

//     counter++;
//   }

//   // console.log(countOfAppointments);
//   APIRESPONSE.dataSetJan.datasets.push({
//     data: countOfAppointments,
//     label: "TotalVisits",
//     borderColor: "#c42150",
//     fill: false,
//   });
// }

// totalAllAppointmentData();
// totalAllAppointmentDataJan();
